config/routes.rb
Rails.application.routes.draw do
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social


 
  devise_for :users, :controllers => { registrations: 'registrations' } do

  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end



    resources :users  do
    member do
      get 'avatar'
      patch 'upload_avatar'
      get 'destroy_avatar'
	  get :call_action
    end
  end

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  #devise_for :users, :controllers => { registrations: 'registrations' }

  resources :conversations, only: [:index, :show, :destroy]

  # mailbox folder routes
   # get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'mailbox/notify_mail', to: 'mailbox#notify_mail', as: :mailbox_notify_mail
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/blank" => "mailbox#blank", as: :mailbox_blank
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash


  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
 # get 'miscellaneous/forgot_password',
 #     to: 'miscellaneous#forgot_password',
 #     as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout false
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
  end
  end

  def show
    @receipts = conversation.receipts_for(current_user).order("created_at ASC")
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end


  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    #flash[:notice] = "Your reply message was successfully sent!"
     respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
  end
end

  def trash
    conversation.move_to_trash(current_user)
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
	end
  end

  def empty_trash
    mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
	end
  end

    def empty_sent
    mailbox.sentbox.each do |conversation|
      conversation.move_to_trash(current_user)
    end
    flash[:success] = 'Your sent was cleaned!'
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
	end
  end

  

    def empty_inbox
    mailbox.inbox.each do |conversation|
      conversation.move_to_trash(current_user)
    end
    flash[:success] = 'Your inbox was cleaned!'
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
	end
  end

  def untrash
    conversation.untrash(current_user)
	 respond_to do |format|
	   format.html { head :no_content }
       format.js
       format.json { head :no_content }
	end
  end




  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject, :training_id )
  end
end

app/views/conversations/_conversation.html.erb
<div>
   <ul class="notification-body">
      <li>
         <% if conversation.is_unread?(current_user) %>
           <% if conversation.last_sender != nil %>
             <span class="unread">
               <a href="javascript:void(0);" class="msg"  onclick="SetNotification('<%= conversation_path(conversation)  %>');">
               <span class="from">From: <%= conversation.last_sender.full_name_first_last %></span>
               <span class="subject">Subject: <%= conversation.subject %></span>
               <time><%=  conversation.messages.last.created_at.strftime("%m/%d/%Y at %I:%M%p") %></time>  
               </a>
             </span>
           <% else %>
             <span class="unread">
               <a href="javascript:void(0);" class="msg"  onclick="SetNotification('<%= conversation_path(conversation)  %>');">
               <span class="from">From: Unknown</span>
               <span class="subject">Subject: <%= conversation.subject %></span>
               <time><%=  conversation.messages.last.created_at.strftime("%m/%d/%Y at %I:%M%p") %></time>  
               </a>
             </span>
           <% end %>  
         <% else %>
         <% if boxname =="sent" %>
         <span>
            <a href="javascript:void(0);" class="msg"  onclick="SetNotification('<%= conversation_path(conversation)  %>');">
               <span class="to">
               To:<% conversation.recipients.uniq.each do |recipient| %>             
               <% unless recipient == current_user %>
               <%=recipient.full_name_first_last %>              
               <% end %>&nbsp;<% end %></span>
               <div style="font-size: 9px;font-weight: normal;color: #058dc7;">
                  <%=  conversation.messages.last.created_at.strftime("%m/%d/%Y at %I:%M%p") %>
               </div>
               <span class="subject">
               Subject: <%= conversation.subject %>
               </span>
            </a>
         </span>
         <% else %>
         <% if conversation.last_sender != nil %>
             <span>
               <a href="javascript:void(0);" class="msg"  onclick="SetNotification('<%= conversation_path(conversation)  %>');">
               <span class="from">From: <%= conversation.last_sender.full_name_first_last %></span>
               <span class="subject">
               Subject: <%= conversation.subject %></span>
               <time><%=  conversation.messages.last.created_at.strftime("%m/%d/%Y at %I:%M%p") %></time>  
               </a>
             </span>
           <% else %>
             <span>
               <a href="javascript:void(0);" class="msg"  onclick="SetNotification('<%= conversation_path(conversation)  %>');">
               <span class="from">From: Unknown</span>
               <span class="subject">
               Subject: <%= conversation.subject %></span>
               <time><%=  conversation.messages.last.created_at.strftime("%m/%d/%Y at %I:%M%p") %></time>  
               </a>
             </span>
           <% end %>   
         <% end %>      
         <% end %>
      </li>
   </ul>
</div>

app/views/conversations/_messages.html.erb
  <div>
    <ul class="notification-body">
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>

		<li>
			<span>
				<a class="msg">
				   <%= image_tag message.sender.photo.url(:thumb), alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				        <span class="from"><%= message.sender.full_name_first_last %></span>
						<!--span class="subject"><%= message.subject %></span-->
						<time><%=  message.created_at.strftime("%m/%d/%Y at %I:%M%p") %></time>
	                    <span class="msg-body"><%= message.body %></span>	  
				</a>
			</span>
       </li> 

<% end %>
   </ul>

   </div>

app/views/conversations/_show.html.erb
<% currently_at "conversations" %>



<!-- widget grid -->
<section id="widget-grid" class="">

  <!-- row -->
  <div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-6 col-sm-6 col-md-6 col-lg-3">


      <!-- Widget ID (each widget will need unique ID)-->
      <div class="jarviswidget jarviswidget-color-darken" id="mailbox-form" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">

        <header>
          <span class="widget-icon">
            <i class="fa fa-envelope"></i>
          </span>
          <h2 id="form-header-title">
            <%= t(:singular, scope: "simple_form.labels.mailbox") %>
          </h2>
        </header>
        <!-- widget div-->
        <div>

		


          <!-- widget edit box -->
          <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

          </div>
          <!-- end widget edit box -->

          <!-- widget content -->
          <div class="widget-body no-padding">
          <div class="well">
              <div class="bottom-buffer">
                <div class="bottom-buffer">
                  <!--      <%= render 'layouts/create', save_path: new_conversation_path, scope: "simple_form.labels.conversation" %> -->
                  <%= link_to "Compose", new_conversation_path, class: "btn btn-success"%>
                </div>

                <!-- START OF FORM -->

                <div id="form-content">
                  <%= render "mailbox/folders" %>
                </div>


              </div>
            </div>
            <!-- end widget div -->
          </div>
        </div>
      </div>
      <!-- end widget -->
    </article>
    <!-- WIDGET END -->


   <!-- NEW WIDGET START -->
    <article class="col-xs-18 col-sm-18 col-md-18 col-lg-9">

      <!-- Widget ID (each widget will need unique ID)-->
      <div class="jarviswidget jarviswidget-color-darken" id="conversation-form" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">

        <header>
          <span class="widget-icon">
            <i class="fa fa-users"></i>
          </span>
          <h2 id="form-header-title">
            <%= t(:plural, scope: "simple_form.labels.conversation") %>
          </h2>
        </header>
        <!-- widget div-->
        <div>
			
          <!-- end widget edit box -->

          <!-- widget content -->
          <div class="widget-body no-padding">
            <div class="well">
              <div class="bottom-buffer">
                <!-- START OF FORM -->
                

                  <p>
				<%= render 'conversations/participants', conversation: @conversation %>
			</p>
                    
            
                    <div class="panel panel-default">
                      <div class="panel-body">
                        <div class="col-md-6 text-right" style="width:100%">
                                        <% if conversation.is_trashed?(current_user) %>
                                                      <%= link_to t(:untrash_message, scope: 'modules'), untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
                                        <% else %>
                                                      <%= link_to t(:move_to_trash, scope: 'modules'), trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                                        data: {confirm: 'Are you sure?'} %>
                                        <% end %>
                        </div>
                        <br></br>
                             <%= render partial: 'messages' %>
                      </div>
                      <div class="panel-footer">
                        <!-- Reply Form -->
                        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
                        <div class="form-group">
                          <%= f.text_area :body, placeholder: t(:reply_message, scope: 'modules'), rows: 4, class: "form-control" %>
                        </div>
                        <%= f.submit t(:reply_message, scope: 'modules'), class: 'btn btn-danger pull-right' %>
						<br></br>
                        <% end %>

                      </div>
                    </div>
           
        


              </div>
            </div>
            <!-- end widget div -->
          </div>
        </div>
      </div>
      <!-- end widget -->
    </article>
    <!-- WIDGET END -->
  </div>
  
  
  
  <!-- end row -->
</section>
<!-- end widget grid -->
  











  
  
    
    

app/views/conversations/create.js.erb
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:sent_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 
 
 var activeClass = '';
                  if (document.getElementById("Inbox").parentElement.className == 'btn btn-default active'){
                    activeClass = 'Inbox'
                    document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
                    loadURL('<%= mailbox_inbox_path %>',  $(".ajax-notifications"));
                  }
                  else if (document.getElementById("Trash").parentElement.className == 'btn btn-default active'){
                    activeClass = 'Trash'
                    document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
                    loadURL('<%= mailbox_trash_path %>',  $(".ajax-notifications"));
                  }
                  else if (document.getElementById("Sent").parentElement.className == 'btn btn-default active'){
                    activeClass = 'Sent'
                    document.getElementById("Sent").value = "<%= mailbox_sent_path %>";
                    loadURL('<%= mailbox_sent_path %>',  $(".ajax-notifications"));
                  }
                  if (activeClass != ''){
                    document.getElementById(activeClass).value = newPath;
                  }
                  if (newPath != ''){
                    loadURL(newPath,  $(".ajax-notifications"));
                  }
                  activeClass = ''
                  document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
                  document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
                  document.getElementById("Sent").value = "<%= mailbox_sent_path %>";

app/views/conversations/empty_sent.js.erb
 
 
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:sent_emptied_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 

loadURL('<%= mailbox_sent_path %>',  $(".ajax-notifications"));

app/views/conversations/empty_trash.js.erb
 
 
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:trash_emptied_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 

loadURL('<%= mailbox_trash_path %>',  $(".ajax-notifications"));

app/views/conversations/reply.js.erb
 
 
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:sent_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 
$('#dt_incidents').DataTable().ajax.reload();

loadURL('<%= conversation_path(conversation)  %>',  $(".ajax-notifications"));

app/views/conversations/show.html.erb
<% currently_at "conversations" %>
<div>
   <div  align="left"></div>
   <div id="form-content">
      <div >
         <div class="panel-header" style="padding: 10px 15px;">
            <table width="100%">
               <tr>
                  <td>
                     <b>Participants: </b>  <%= render 'conversations/participants', conversation: @conversation %>
                  </td>
                  <td align="right">
                     <% if conversation.is_trashed?(current_user) %>
                     <%= link_to untrash_conversation_path(conversation), remote:true, class: 'btn btn-info btn-xs', method: :post, data: {confirm: t(:button_confirm, scope: "buttons"), ok: t(:yes_button, scope: "buttons"), cancel: t(:cancel, scope: "buttons")} do %>
                     <i class="fa fa-undo"></i> <!--%= t(:untrash_message, scope: 'buttons')%-->
                     <% end %>
                     <% else %>
                     <%= link_to trash_conversation_path(conversation), remote:true, class: 'btn btn-danger btn-xs', method: :post, data: {confirm: t(:button_confirm, scope: "buttons"), ok: t(:yes_button, scope: "buttons"), cancel: t(:cancel, scope: "buttons")} do %>
                     <i class="fa fa-trash"></i> <!--%= t(:move_to_trash, scope: 'buttons')%-->
                     <% end %>
                     <% end %>
                  </td>
               </tr>
            </table>
         </div>
         <div class="panel-header" style="padding: 10px 15px;">
            <p><b>Subject: </b><%= conversation.subject  %> </p>
         </div>
         <div  align="left">
            <ul class="notification-body">
               <span>
               <%= render partial: 'messages', remote: true %>
               </span>
               <body>
                  <div class="panel-footer">

                     <!-- Reply Form -->
                     <%= form_for :message, url: reply_conversation_path(conversation), remote:true do |f| %>
                     <div  align="center">
                        <%= f.text_area :body, placeholder: t(:reply_message), style: 'width:240px', class: 'form-control', rows: 3 %>
                        <div align="center" style="margin-top:7px !important">
                           <%= button_tag( :class => "btn btn-success") do %>
                           <i class="fa fa-send"> </i> <%= t(:reply_message)%>
                           <% end %>
                        </div>
                     </div>
					 <% end %>
            
                  </div>
               </body>
            </ul >
         </div>
      </div>
   </div>
</div>

app/views/conversations/show.js.erb
 
 
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:sent_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 
$('#dt_incidents').DataTable().ajax.reload();

loadURL('<%= conversation_path(conversation)  %>',  $(".ajax-notifications"));

app/views/conversations/trash.js.erb
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:trashed_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 
var activeClass = '';
if (document.getElementById("Inbox").parentElement.className == 'btn btn-default active'){
activeClass = 'Inbox'
document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
loadURL('<%= mailbox_inbox_path %>',  $(".ajax-notifications"));
}
else if (document.getElementById("Trash").parentElement.className == 'btn btn-default active'){
	activeClass = 'Trash'
	document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
	loadURL('<%= mailbox_trash_path %>',  $(".ajax-notifications"));
}
else if (document.getElementById("Sent").parentElement.className == 'btn btn-default active'){
	activeClass = 'Sent'
	document.getElementById("Sent").value = "<%= mailbox_sent_path %>";
	loadURL('<%= mailbox_sent_path %>',  $(".ajax-notifications"));
}
else
{
	loadURL('<%= mailbox_inbox_path %>',  $(".ajax-notifications"));
	document.getElementById("Inbox").parentElement.className = 'btn btn-default active'
}
if (activeClass != ''){
	document.getElementById(activeClass).value = newPath;
}
if (newPath != ''){
	loadURL(newPath,  $(".ajax-notifications"));
}
activeClass = ''
document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
document.getElementById("Sent").value = "<%= mailbox_sent_path %>";

app/views/conversations/untrash.js.erb
 $.smallBox({
	title : "<%= t(:mailbox, scope: 'modules') %>",
	content : "<%= t(:untrashed_message) %>",
	color : "#4c4f53",
	iconSmall : "fa fa-envelope-o bounce animated",
	timeout : 2000,
	sound: false
});
 
 
var activeClass = '';
if (document.getElementById("Inbox").parentElement.className == 'btn btn-default active'){
activeClass = 'Inbox'
document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
loadURL('<%= mailbox_inbox_path %>',  $(".ajax-notifications"));
}
else if (document.getElementById("Trash").parentElement.className == 'btn btn-default active'){
	activeClass = 'Trash'
	document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
	loadURL('<%= mailbox_trash_path %>',  $(".ajax-notifications"));
}
else if (document.getElementById("Sent").parentElement.className == 'btn btn-default active'){
	activeClass = 'Sent'
	document.getElementById("Sent").value = "<%= mailbox_sent_path %>";
	loadURL('<%= mailbox_sent_path %>',  $(".ajax-notifications"));
}
else
{
	loadURL('<%= mailbox_inbox_path %>',  $(".ajax-notifications"));
	document.getElementById("Inbox").parentElement.className = 'btn btn-default active'
}
if (activeClass != ''){
	document.getElementById(activeClass).value = newPath;
}
if (newPath != ''){
	loadURL(newPath,  $(".ajax-notifications"));
}
activeClass = ''
document.getElementById("Inbox").value = "<%= mailbox_inbox_path %>";
document.getElementById("Trash").value = "<%= mailbox_trash_path %>";
document.getElementById("Sent").value = "<%= mailbox_sent_path %>";