config/routes.rb
Rails.application.routes.draw do
 # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social


 
  devise_for :users, :controllers => { registrations: 'registrations' } do

  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end



    resources :users  do
    member do
      get 'avatar'
      patch 'upload_avatar'
      get 'destroy_avatar'
	  get :call_action
    end
  end

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  #devise_for :users, :controllers => { registrations: 'registrations' }

  resources :conversations, only: [:index, :show, :destroy]

  # mailbox folder routes
   # get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'mailbox/notify_mail', to: 'mailbox#notify_mail', as: :mailbox_notify_mail
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/blank" => "mailbox#blank", as: :mailbox_blank
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash


  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
 # get 'miscellaneous/forgot_password',
 #     to: 'miscellaneous#forgot_password',
 #     as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/controllers/outlook_controller.rb
# Outlook section
class OutlookController < ApplicationController
  def inbox
  end
end

app/views/outlook/inbox.html.erb
<% content_for :ribbon do %>
<!-- RIBBON -->
<div id="ribbon">

				<span class="ribbon-button-alignment">
					<span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
						<i class="fa fa-refresh"></i>
					</span>
				</span>

  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li>Home</li><li>Inbox</li>
  </ol>
  <!-- end breadcrumb -->

  <!-- You can also add more buttons to the
  ribbon for further usability

  Example below:

  <span class="ribbon-button-alignment pull-right">
  <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
  <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
  <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
  </span> -->

</div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <div class="inbox-nav-bar no-content-padding">

    <h1 class="page-title txt-color-blueDark hidden-tablet"><i class="fa fa-fw fa-inbox"></i> Inbox &nbsp;
						<span class="btn-group">
							<a href="#" data-toggle="dropdown" class="btn btn-default btn-xs dropdown-toggle"><span class="caret single"></span></a>
							<ul class="dropdown-menu">
                <li>
                  <a href="#">Action</a>
                </li>
                <li>
                  <a href="#">Another action</a>
                </li>
                <li>
                  <a href="#">Something else here</a>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="#">Separated link</a>
                </li>
              </ul>
						</span>
    </h1>

    <div class="btn-group hidden-desktop visible-tablet">
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Inbox <i class="fa fa-caret-down"></i>
      </button>
      <ul class="dropdown-menu pull-left">
        <li>
          <a href="javascript:void(0);" class="inbox-load">Inbox <i class="fa fa-check"></i></a>
        </li>
        <li>
          <a href="javascript:void(0);">Sent</a>
        </li>
        <li>
          <a href="javascript:void(0);">Trash</a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="javascript:void(0);">Spam</a>
        </li>
      </ul>

    </div>

    <div class="inbox-checkbox-triggered">

      <div class="btn-group">
        <a href="javascript:void(0);" rel="tooltip" title="" data-placement="bottom" data-original-title="Mark Important" class="btn btn-default"><strong><i class="fa fa-exclamation fa-lg text-danger"></i></strong></a>
        <a href="javascript:void(0);" rel="tooltip" title="" data-placement="bottom" data-original-title="Move to folder" class="btn btn-default"><strong><i class="fa fa-folder-open fa-lg"></i></strong></a>
        <a href="javascript:void(0);" rel="tooltip" title="" data-placement="bottom" data-original-title="Delete" class="deletebutton btn btn-default"><strong><i class="fa fa-trash-o fa-lg"></i></strong></a>
      </div>

    </div>

    <a href="javascript:void(0);" id="compose-mail-mini" class="btn btn-primary pull-right hidden-desktop visible-tablet"> <strong><i class="fa fa-file fa-lg"></i></strong> </a>

    <div class="btn-group pull-right inbox-paging">
      <a href="javascript:void(0);" class="btn btn-default btn-sm"><strong><i class="fa fa-chevron-left"></i></strong></a>
      <a href="javascript:void(0);" class="btn btn-default btn-sm"><strong><i class="fa fa-chevron-right"></i></strong></a>
    </div>
    <span class="pull-right"><strong>1-30</strong> of <strong>3,452</strong></span>

  </div>

  <div id="inbox-content" class="inbox-body no-content-padding">

    <div class="inbox-side-bar">

      <a href="javascript:void(0);" id="compose-mail" class="btn btn-primary btn-block"> <strong>Compose</strong> </a>

      <h6> Folder <a href="javascript:void(0);" rel="tooltip" title="" data-placement="right" data-original-title="Refresh" class="pull-right txt-color-darken"><i class="fa fa-refresh"></i></a></h6>

      <ul class="inbox-menu-lg">
        <li class="active">
          <a class="inbox-load" href="javascript:void(0);"> Inbox (14) </a>
        </li>
        <li>
          <a href="javascript:void(0);">Sent</a>
        </li>
        <li>
          <a href="javascript:void(0);">Draft</a>
        </li>
        <li>
          <a href="javascript:void(0);">Trash</a>
        </li>
      </ul>

      <h6> Quick Access <a href="javascript:void(0);" rel="tooltip" title="" data-placement="right" data-original-title="Add Another" class="pull-right txt-color-darken"><i class="fa fa-plus"></i></a></h6>

      <ul class="inbox-menu-sm">
        <li>
          <a href="javascript:void(0);"> Images (476)</a>
        </li>
        <li>
          <a href="javascript:void(0);">Documents (4)</a>
        </li>
      </ul>

      <div class="air air-bottom inbox-space">

        3.5GB of <strong>10GB</strong><a href="javascript:void(0);" rel="tooltip" title="" data-placement="top" data-original-title="Empty Spam" class="pull-right txt-color-darken"><i class="fa fa-trash-o fa-lg"></i></a>

        <div class="progress progress-micro">
          <div class="progress-bar progress-primary" style="width: 34%;"></div>
        </div>
      </div>

    </div>

    <div class="table-wrap custom-scroll animated fast fadeInRight">
      <!-- ajax will fill this area -->
      LOADING...

    </div>

    <div class="inbox-footer">

      <div class="row">

        <div class="col-xs-6 col-sm-1">

          <div class="txt-color-white hidden-desktop visible-mobile">
            3.5GB of <strong>10GB</strong>

            <div class="progress progress-micro">
              <div class="progress-bar progress-primary" style="width: 34%;"></div>
            </div>
          </div>
        </div>

        <div class="col-xs-6 col-sm-11 text-right">
          <div class="txt-color-white inline-block">
            <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> 52 mins ago |</i> Displaying <strong>44 of 259</strong>
          </div>
        </div>

      </div>

    </div>

  </div>


</div>
<!-- END MAIN CONTENT -->
<% content_for :scripts do %>
  <script type="text/javascript">

    $(document).ready(function() {

      // DO NOT REMOVE : GLOBAL FUNCTIONS!
      pageSetUp();

      // PAGE RELATED SCRIPTS

      /*
       * Fixed table height
       */

      //tableHeightSize()

      //$(window).resize(function() {
      //	tableHeightSize()
      //})

      function tableHeightSize() {

        if ($('body').hasClass('menu-on-top')) {
          var menuHeight = 68;
          // nav height

          var tableHeight = ($(window).height() - 224) - menuHeight;
          if (tableHeight < (320 - menuHeight)) {
            $('.table-wrap').css('height', (320 - menuHeight) + 'px');
          } else {
            $('.table-wrap').css('height', tableHeight + 'px');
          }

        } else {
          var tableHeight = $(window).height() - 224;
          if (tableHeight < 320) {
            $('.table-wrap').css('height', 320 + 'px');
          } else {
            $('.table-wrap').css('height', tableHeight + 'px');
          }

        }

      }

      /*
       * LOAD INBOX MESSAGES
       */
      loadInbox();
      function loadInbox() {
        loadURL("<%= ajax_email_list_path %>", $('#inbox-content > .table-wrap'))
      }

      /*
       * Buttons (compose mail and inbox load)
       */
      $(".inbox-load").click(function() {
        loadInbox();
      });

      // compose email
      $("#compose-mail").click(function() {
        loadURL("<%= ajax_email_compose_path %>", $('#inbox-content > .table-wrap'));
      })

    });


  </script>
<% end %>